
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `ContinueWatching` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ContinueWatching
 * 
 */
export type ContinueWatchingModel = runtime.Types.Result.DefaultSelection<Prisma.$ContinueWatchingPayload>

export type AggregateContinueWatching = {
  _count: ContinueWatchingCountAggregateOutputType | null
  _avg: ContinueWatchingAvgAggregateOutputType | null
  _sum: ContinueWatchingSumAggregateOutputType | null
  _min: ContinueWatchingMinAggregateOutputType | null
  _max: ContinueWatchingMaxAggregateOutputType | null
}

export type ContinueWatchingAvgAggregateOutputType = {
  tmdbId: number | null
  season: number | null
  episode: number | null
}

export type ContinueWatchingSumAggregateOutputType = {
  tmdbId: number | null
  season: number | null
  episode: number | null
}

export type ContinueWatchingMinAggregateOutputType = {
  id: string | null
  userId: string | null
  tmdbId: number | null
  type: string | null
  season: number | null
  episode: number | null
}

export type ContinueWatchingMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  tmdbId: number | null
  type: string | null
  season: number | null
  episode: number | null
}

export type ContinueWatchingCountAggregateOutputType = {
  id: number
  userId: number
  tmdbId: number
  type: number
  season: number
  episode: number
  _all: number
}


export type ContinueWatchingAvgAggregateInputType = {
  tmdbId?: true
  season?: true
  episode?: true
}

export type ContinueWatchingSumAggregateInputType = {
  tmdbId?: true
  season?: true
  episode?: true
}

export type ContinueWatchingMinAggregateInputType = {
  id?: true
  userId?: true
  tmdbId?: true
  type?: true
  season?: true
  episode?: true
}

export type ContinueWatchingMaxAggregateInputType = {
  id?: true
  userId?: true
  tmdbId?: true
  type?: true
  season?: true
  episode?: true
}

export type ContinueWatchingCountAggregateInputType = {
  id?: true
  userId?: true
  tmdbId?: true
  type?: true
  season?: true
  episode?: true
  _all?: true
}

export type ContinueWatchingAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ContinueWatching to aggregate.
   */
  where?: Prisma.ContinueWatchingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContinueWatchings to fetch.
   */
  orderBy?: Prisma.ContinueWatchingOrderByWithRelationInput | Prisma.ContinueWatchingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ContinueWatchingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContinueWatchings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContinueWatchings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned ContinueWatchings
  **/
  _count?: true | ContinueWatchingCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ContinueWatchingAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ContinueWatchingSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ContinueWatchingMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ContinueWatchingMaxAggregateInputType
}

export type GetContinueWatchingAggregateType<T extends ContinueWatchingAggregateArgs> = {
      [P in keyof T & keyof AggregateContinueWatching]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateContinueWatching[P]>
    : Prisma.GetScalarType<T[P], AggregateContinueWatching[P]>
}




export type ContinueWatchingGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ContinueWatchingWhereInput
  orderBy?: Prisma.ContinueWatchingOrderByWithAggregationInput | Prisma.ContinueWatchingOrderByWithAggregationInput[]
  by: Prisma.ContinueWatchingScalarFieldEnum[] | Prisma.ContinueWatchingScalarFieldEnum
  having?: Prisma.ContinueWatchingScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ContinueWatchingCountAggregateInputType | true
  _avg?: ContinueWatchingAvgAggregateInputType
  _sum?: ContinueWatchingSumAggregateInputType
  _min?: ContinueWatchingMinAggregateInputType
  _max?: ContinueWatchingMaxAggregateInputType
}

export type ContinueWatchingGroupByOutputType = {
  id: string
  userId: string
  tmdbId: number
  type: string
  season: number | null
  episode: number | null
  _count: ContinueWatchingCountAggregateOutputType | null
  _avg: ContinueWatchingAvgAggregateOutputType | null
  _sum: ContinueWatchingSumAggregateOutputType | null
  _min: ContinueWatchingMinAggregateOutputType | null
  _max: ContinueWatchingMaxAggregateOutputType | null
}

type GetContinueWatchingGroupByPayload<T extends ContinueWatchingGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ContinueWatchingGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ContinueWatchingGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ContinueWatchingGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ContinueWatchingGroupByOutputType[P]>
      }
    >
  >



export type ContinueWatchingWhereInput = {
  AND?: Prisma.ContinueWatchingWhereInput | Prisma.ContinueWatchingWhereInput[]
  OR?: Prisma.ContinueWatchingWhereInput[]
  NOT?: Prisma.ContinueWatchingWhereInput | Prisma.ContinueWatchingWhereInput[]
  id?: Prisma.StringFilter<"ContinueWatching"> | string
  userId?: Prisma.StringFilter<"ContinueWatching"> | string
  tmdbId?: Prisma.IntFilter<"ContinueWatching"> | number
  type?: Prisma.StringFilter<"ContinueWatching"> | string
  season?: Prisma.IntNullableFilter<"ContinueWatching"> | number | null
  episode?: Prisma.IntNullableFilter<"ContinueWatching"> | number | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type ContinueWatchingOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  tmdbId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  season?: Prisma.SortOrderInput | Prisma.SortOrder
  episode?: Prisma.SortOrderInput | Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
}

export type ContinueWatchingWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_tmdbId_type?: Prisma.ContinueWatchingUserIdTmdbIdTypeCompoundUniqueInput
  AND?: Prisma.ContinueWatchingWhereInput | Prisma.ContinueWatchingWhereInput[]
  OR?: Prisma.ContinueWatchingWhereInput[]
  NOT?: Prisma.ContinueWatchingWhereInput | Prisma.ContinueWatchingWhereInput[]
  userId?: Prisma.StringFilter<"ContinueWatching"> | string
  tmdbId?: Prisma.IntFilter<"ContinueWatching"> | number
  type?: Prisma.StringFilter<"ContinueWatching"> | string
  season?: Prisma.IntNullableFilter<"ContinueWatching"> | number | null
  episode?: Prisma.IntNullableFilter<"ContinueWatching"> | number | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "userId_tmdbId_type">

export type ContinueWatchingOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  tmdbId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  season?: Prisma.SortOrderInput | Prisma.SortOrder
  episode?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ContinueWatchingCountOrderByAggregateInput
  _avg?: Prisma.ContinueWatchingAvgOrderByAggregateInput
  _max?: Prisma.ContinueWatchingMaxOrderByAggregateInput
  _min?: Prisma.ContinueWatchingMinOrderByAggregateInput
  _sum?: Prisma.ContinueWatchingSumOrderByAggregateInput
}

export type ContinueWatchingScalarWhereWithAggregatesInput = {
  AND?: Prisma.ContinueWatchingScalarWhereWithAggregatesInput | Prisma.ContinueWatchingScalarWhereWithAggregatesInput[]
  OR?: Prisma.ContinueWatchingScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ContinueWatchingScalarWhereWithAggregatesInput | Prisma.ContinueWatchingScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"ContinueWatching"> | string
  userId?: Prisma.StringWithAggregatesFilter<"ContinueWatching"> | string
  tmdbId?: Prisma.IntWithAggregatesFilter<"ContinueWatching"> | number
  type?: Prisma.StringWithAggregatesFilter<"ContinueWatching"> | string
  season?: Prisma.IntNullableWithAggregatesFilter<"ContinueWatching"> | number | null
  episode?: Prisma.IntNullableWithAggregatesFilter<"ContinueWatching"> | number | null
}

export type ContinueWatchingCreateInput = {
  id?: string
  tmdbId: number
  type: string
  season?: number | null
  episode?: number | null
  user: Prisma.UserCreateNestedOneWithoutContinueWatchingInput
}

export type ContinueWatchingUncheckedCreateInput = {
  id?: string
  userId: string
  tmdbId: number
  type: string
  season?: number | null
  episode?: number | null
}

export type ContinueWatchingUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tmdbId?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  episode?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  user?: Prisma.UserUpdateOneRequiredWithoutContinueWatchingNestedInput
}

export type ContinueWatchingUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  tmdbId?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  episode?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ContinueWatchingCreateManyInput = {
  id?: string
  userId: string
  tmdbId: number
  type: string
  season?: number | null
  episode?: number | null
}

export type ContinueWatchingUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tmdbId?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  episode?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ContinueWatchingUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  tmdbId?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  episode?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ContinueWatchingListRelationFilter = {
  every?: Prisma.ContinueWatchingWhereInput
  some?: Prisma.ContinueWatchingWhereInput
  none?: Prisma.ContinueWatchingWhereInput
}

export type ContinueWatchingOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ContinueWatchingUserIdTmdbIdTypeCompoundUniqueInput = {
  userId: string
  tmdbId: number
  type: string
}

export type ContinueWatchingCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  tmdbId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  season?: Prisma.SortOrder
  episode?: Prisma.SortOrder
}

export type ContinueWatchingAvgOrderByAggregateInput = {
  tmdbId?: Prisma.SortOrder
  season?: Prisma.SortOrder
  episode?: Prisma.SortOrder
}

export type ContinueWatchingMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  tmdbId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  season?: Prisma.SortOrder
  episode?: Prisma.SortOrder
}

export type ContinueWatchingMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  tmdbId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  season?: Prisma.SortOrder
  episode?: Prisma.SortOrder
}

export type ContinueWatchingSumOrderByAggregateInput = {
  tmdbId?: Prisma.SortOrder
  season?: Prisma.SortOrder
  episode?: Prisma.SortOrder
}

export type ContinueWatchingCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ContinueWatchingCreateWithoutUserInput, Prisma.ContinueWatchingUncheckedCreateWithoutUserInput> | Prisma.ContinueWatchingCreateWithoutUserInput[] | Prisma.ContinueWatchingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ContinueWatchingCreateOrConnectWithoutUserInput | Prisma.ContinueWatchingCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ContinueWatchingCreateManyUserInputEnvelope
  connect?: Prisma.ContinueWatchingWhereUniqueInput | Prisma.ContinueWatchingWhereUniqueInput[]
}

export type ContinueWatchingUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ContinueWatchingCreateWithoutUserInput, Prisma.ContinueWatchingUncheckedCreateWithoutUserInput> | Prisma.ContinueWatchingCreateWithoutUserInput[] | Prisma.ContinueWatchingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ContinueWatchingCreateOrConnectWithoutUserInput | Prisma.ContinueWatchingCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ContinueWatchingCreateManyUserInputEnvelope
  connect?: Prisma.ContinueWatchingWhereUniqueInput | Prisma.ContinueWatchingWhereUniqueInput[]
}

export type ContinueWatchingUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ContinueWatchingCreateWithoutUserInput, Prisma.ContinueWatchingUncheckedCreateWithoutUserInput> | Prisma.ContinueWatchingCreateWithoutUserInput[] | Prisma.ContinueWatchingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ContinueWatchingCreateOrConnectWithoutUserInput | Prisma.ContinueWatchingCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ContinueWatchingUpsertWithWhereUniqueWithoutUserInput | Prisma.ContinueWatchingUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ContinueWatchingCreateManyUserInputEnvelope
  set?: Prisma.ContinueWatchingWhereUniqueInput | Prisma.ContinueWatchingWhereUniqueInput[]
  disconnect?: Prisma.ContinueWatchingWhereUniqueInput | Prisma.ContinueWatchingWhereUniqueInput[]
  delete?: Prisma.ContinueWatchingWhereUniqueInput | Prisma.ContinueWatchingWhereUniqueInput[]
  connect?: Prisma.ContinueWatchingWhereUniqueInput | Prisma.ContinueWatchingWhereUniqueInput[]
  update?: Prisma.ContinueWatchingUpdateWithWhereUniqueWithoutUserInput | Prisma.ContinueWatchingUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ContinueWatchingUpdateManyWithWhereWithoutUserInput | Prisma.ContinueWatchingUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ContinueWatchingScalarWhereInput | Prisma.ContinueWatchingScalarWhereInput[]
}

export type ContinueWatchingUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ContinueWatchingCreateWithoutUserInput, Prisma.ContinueWatchingUncheckedCreateWithoutUserInput> | Prisma.ContinueWatchingCreateWithoutUserInput[] | Prisma.ContinueWatchingUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ContinueWatchingCreateOrConnectWithoutUserInput | Prisma.ContinueWatchingCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ContinueWatchingUpsertWithWhereUniqueWithoutUserInput | Prisma.ContinueWatchingUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ContinueWatchingCreateManyUserInputEnvelope
  set?: Prisma.ContinueWatchingWhereUniqueInput | Prisma.ContinueWatchingWhereUniqueInput[]
  disconnect?: Prisma.ContinueWatchingWhereUniqueInput | Prisma.ContinueWatchingWhereUniqueInput[]
  delete?: Prisma.ContinueWatchingWhereUniqueInput | Prisma.ContinueWatchingWhereUniqueInput[]
  connect?: Prisma.ContinueWatchingWhereUniqueInput | Prisma.ContinueWatchingWhereUniqueInput[]
  update?: Prisma.ContinueWatchingUpdateWithWhereUniqueWithoutUserInput | Prisma.ContinueWatchingUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ContinueWatchingUpdateManyWithWhereWithoutUserInput | Prisma.ContinueWatchingUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ContinueWatchingScalarWhereInput | Prisma.ContinueWatchingScalarWhereInput[]
}

export type ContinueWatchingCreateWithoutUserInput = {
  id?: string
  tmdbId: number
  type: string
  season?: number | null
  episode?: number | null
}

export type ContinueWatchingUncheckedCreateWithoutUserInput = {
  id?: string
  tmdbId: number
  type: string
  season?: number | null
  episode?: number | null
}

export type ContinueWatchingCreateOrConnectWithoutUserInput = {
  where: Prisma.ContinueWatchingWhereUniqueInput
  create: Prisma.XOR<Prisma.ContinueWatchingCreateWithoutUserInput, Prisma.ContinueWatchingUncheckedCreateWithoutUserInput>
}

export type ContinueWatchingCreateManyUserInputEnvelope = {
  data: Prisma.ContinueWatchingCreateManyUserInput | Prisma.ContinueWatchingCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ContinueWatchingUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ContinueWatchingWhereUniqueInput
  update: Prisma.XOR<Prisma.ContinueWatchingUpdateWithoutUserInput, Prisma.ContinueWatchingUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ContinueWatchingCreateWithoutUserInput, Prisma.ContinueWatchingUncheckedCreateWithoutUserInput>
}

export type ContinueWatchingUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ContinueWatchingWhereUniqueInput
  data: Prisma.XOR<Prisma.ContinueWatchingUpdateWithoutUserInput, Prisma.ContinueWatchingUncheckedUpdateWithoutUserInput>
}

export type ContinueWatchingUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ContinueWatchingScalarWhereInput
  data: Prisma.XOR<Prisma.ContinueWatchingUpdateManyMutationInput, Prisma.ContinueWatchingUncheckedUpdateManyWithoutUserInput>
}

export type ContinueWatchingScalarWhereInput = {
  AND?: Prisma.ContinueWatchingScalarWhereInput | Prisma.ContinueWatchingScalarWhereInput[]
  OR?: Prisma.ContinueWatchingScalarWhereInput[]
  NOT?: Prisma.ContinueWatchingScalarWhereInput | Prisma.ContinueWatchingScalarWhereInput[]
  id?: Prisma.StringFilter<"ContinueWatching"> | string
  userId?: Prisma.StringFilter<"ContinueWatching"> | string
  tmdbId?: Prisma.IntFilter<"ContinueWatching"> | number
  type?: Prisma.StringFilter<"ContinueWatching"> | string
  season?: Prisma.IntNullableFilter<"ContinueWatching"> | number | null
  episode?: Prisma.IntNullableFilter<"ContinueWatching"> | number | null
}

export type ContinueWatchingCreateManyUserInput = {
  id?: string
  tmdbId: number
  type: string
  season?: number | null
  episode?: number | null
}

export type ContinueWatchingUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tmdbId?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  episode?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ContinueWatchingUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tmdbId?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  episode?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}

export type ContinueWatchingUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  tmdbId?: Prisma.IntFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  season?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
  episode?: Prisma.NullableIntFieldUpdateOperationsInput | number | null
}



export type ContinueWatchingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  tmdbId?: boolean
  type?: boolean
  season?: boolean
  episode?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["continueWatching"]>

export type ContinueWatchingSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  tmdbId?: boolean
  type?: boolean
  season?: boolean
  episode?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["continueWatching"]>

export type ContinueWatchingSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  tmdbId?: boolean
  type?: boolean
  season?: boolean
  episode?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["continueWatching"]>

export type ContinueWatchingSelectScalar = {
  id?: boolean
  userId?: boolean
  tmdbId?: boolean
  type?: boolean
  season?: boolean
  episode?: boolean
}

export type ContinueWatchingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "tmdbId" | "type" | "season" | "episode", ExtArgs["result"]["continueWatching"]>
export type ContinueWatchingInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ContinueWatchingIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type ContinueWatchingIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $ContinueWatchingPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "ContinueWatching"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    tmdbId: number
    type: string
    season: number | null
    episode: number | null
  }, ExtArgs["result"]["continueWatching"]>
  composites: {}
}

export type ContinueWatchingGetPayload<S extends boolean | null | undefined | ContinueWatchingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ContinueWatchingPayload, S>

export type ContinueWatchingCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ContinueWatchingFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ContinueWatchingCountAggregateInputType | true
  }

export interface ContinueWatchingDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['ContinueWatching'], meta: { name: 'ContinueWatching' } }
  /**
   * Find zero or one ContinueWatching that matches the filter.
   * @param {ContinueWatchingFindUniqueArgs} args - Arguments to find a ContinueWatching
   * @example
   * // Get one ContinueWatching
   * const continueWatching = await prisma.continueWatching.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ContinueWatchingFindUniqueArgs>(args: Prisma.SelectSubset<T, ContinueWatchingFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ContinueWatchingClient<runtime.Types.Result.GetResult<Prisma.$ContinueWatchingPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one ContinueWatching that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ContinueWatchingFindUniqueOrThrowArgs} args - Arguments to find a ContinueWatching
   * @example
   * // Get one ContinueWatching
   * const continueWatching = await prisma.continueWatching.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ContinueWatchingFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ContinueWatchingFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ContinueWatchingClient<runtime.Types.Result.GetResult<Prisma.$ContinueWatchingPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ContinueWatching that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContinueWatchingFindFirstArgs} args - Arguments to find a ContinueWatching
   * @example
   * // Get one ContinueWatching
   * const continueWatching = await prisma.continueWatching.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ContinueWatchingFindFirstArgs>(args?: Prisma.SelectSubset<T, ContinueWatchingFindFirstArgs<ExtArgs>>): Prisma.Prisma__ContinueWatchingClient<runtime.Types.Result.GetResult<Prisma.$ContinueWatchingPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first ContinueWatching that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContinueWatchingFindFirstOrThrowArgs} args - Arguments to find a ContinueWatching
   * @example
   * // Get one ContinueWatching
   * const continueWatching = await prisma.continueWatching.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ContinueWatchingFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ContinueWatchingFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ContinueWatchingClient<runtime.Types.Result.GetResult<Prisma.$ContinueWatchingPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more ContinueWatchings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContinueWatchingFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all ContinueWatchings
   * const continueWatchings = await prisma.continueWatching.findMany()
   * 
   * // Get first 10 ContinueWatchings
   * const continueWatchings = await prisma.continueWatching.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const continueWatchingWithIdOnly = await prisma.continueWatching.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ContinueWatchingFindManyArgs>(args?: Prisma.SelectSubset<T, ContinueWatchingFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContinueWatchingPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a ContinueWatching.
   * @param {ContinueWatchingCreateArgs} args - Arguments to create a ContinueWatching.
   * @example
   * // Create one ContinueWatching
   * const ContinueWatching = await prisma.continueWatching.create({
   *   data: {
   *     // ... data to create a ContinueWatching
   *   }
   * })
   * 
   */
  create<T extends ContinueWatchingCreateArgs>(args: Prisma.SelectSubset<T, ContinueWatchingCreateArgs<ExtArgs>>): Prisma.Prisma__ContinueWatchingClient<runtime.Types.Result.GetResult<Prisma.$ContinueWatchingPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many ContinueWatchings.
   * @param {ContinueWatchingCreateManyArgs} args - Arguments to create many ContinueWatchings.
   * @example
   * // Create many ContinueWatchings
   * const continueWatching = await prisma.continueWatching.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ContinueWatchingCreateManyArgs>(args?: Prisma.SelectSubset<T, ContinueWatchingCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many ContinueWatchings and returns the data saved in the database.
   * @param {ContinueWatchingCreateManyAndReturnArgs} args - Arguments to create many ContinueWatchings.
   * @example
   * // Create many ContinueWatchings
   * const continueWatching = await prisma.continueWatching.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many ContinueWatchings and only return the `id`
   * const continueWatchingWithIdOnly = await prisma.continueWatching.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ContinueWatchingCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ContinueWatchingCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContinueWatchingPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a ContinueWatching.
   * @param {ContinueWatchingDeleteArgs} args - Arguments to delete one ContinueWatching.
   * @example
   * // Delete one ContinueWatching
   * const ContinueWatching = await prisma.continueWatching.delete({
   *   where: {
   *     // ... filter to delete one ContinueWatching
   *   }
   * })
   * 
   */
  delete<T extends ContinueWatchingDeleteArgs>(args: Prisma.SelectSubset<T, ContinueWatchingDeleteArgs<ExtArgs>>): Prisma.Prisma__ContinueWatchingClient<runtime.Types.Result.GetResult<Prisma.$ContinueWatchingPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one ContinueWatching.
   * @param {ContinueWatchingUpdateArgs} args - Arguments to update one ContinueWatching.
   * @example
   * // Update one ContinueWatching
   * const continueWatching = await prisma.continueWatching.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ContinueWatchingUpdateArgs>(args: Prisma.SelectSubset<T, ContinueWatchingUpdateArgs<ExtArgs>>): Prisma.Prisma__ContinueWatchingClient<runtime.Types.Result.GetResult<Prisma.$ContinueWatchingPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more ContinueWatchings.
   * @param {ContinueWatchingDeleteManyArgs} args - Arguments to filter ContinueWatchings to delete.
   * @example
   * // Delete a few ContinueWatchings
   * const { count } = await prisma.continueWatching.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ContinueWatchingDeleteManyArgs>(args?: Prisma.SelectSubset<T, ContinueWatchingDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ContinueWatchings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContinueWatchingUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many ContinueWatchings
   * const continueWatching = await prisma.continueWatching.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ContinueWatchingUpdateManyArgs>(args: Prisma.SelectSubset<T, ContinueWatchingUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more ContinueWatchings and returns the data updated in the database.
   * @param {ContinueWatchingUpdateManyAndReturnArgs} args - Arguments to update many ContinueWatchings.
   * @example
   * // Update many ContinueWatchings
   * const continueWatching = await prisma.continueWatching.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more ContinueWatchings and only return the `id`
   * const continueWatchingWithIdOnly = await prisma.continueWatching.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ContinueWatchingUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ContinueWatchingUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ContinueWatchingPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one ContinueWatching.
   * @param {ContinueWatchingUpsertArgs} args - Arguments to update or create a ContinueWatching.
   * @example
   * // Update or create a ContinueWatching
   * const continueWatching = await prisma.continueWatching.upsert({
   *   create: {
   *     // ... data to create a ContinueWatching
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the ContinueWatching we want to update
   *   }
   * })
   */
  upsert<T extends ContinueWatchingUpsertArgs>(args: Prisma.SelectSubset<T, ContinueWatchingUpsertArgs<ExtArgs>>): Prisma.Prisma__ContinueWatchingClient<runtime.Types.Result.GetResult<Prisma.$ContinueWatchingPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of ContinueWatchings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContinueWatchingCountArgs} args - Arguments to filter ContinueWatchings to count.
   * @example
   * // Count the number of ContinueWatchings
   * const count = await prisma.continueWatching.count({
   *   where: {
   *     // ... the filter for the ContinueWatchings we want to count
   *   }
   * })
  **/
  count<T extends ContinueWatchingCountArgs>(
    args?: Prisma.Subset<T, ContinueWatchingCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ContinueWatchingCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a ContinueWatching.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContinueWatchingAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ContinueWatchingAggregateArgs>(args: Prisma.Subset<T, ContinueWatchingAggregateArgs>): Prisma.PrismaPromise<GetContinueWatchingAggregateType<T>>

  /**
   * Group by ContinueWatching.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ContinueWatchingGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ContinueWatchingGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ContinueWatchingGroupByArgs['orderBy'] }
      : { orderBy?: ContinueWatchingGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ContinueWatchingGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetContinueWatchingGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the ContinueWatching model
 */
readonly fields: ContinueWatchingFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for ContinueWatching.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ContinueWatchingClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the ContinueWatching model
 */
export interface ContinueWatchingFieldRefs {
  readonly id: Prisma.FieldRef<"ContinueWatching", 'String'>
  readonly userId: Prisma.FieldRef<"ContinueWatching", 'String'>
  readonly tmdbId: Prisma.FieldRef<"ContinueWatching", 'Int'>
  readonly type: Prisma.FieldRef<"ContinueWatching", 'String'>
  readonly season: Prisma.FieldRef<"ContinueWatching", 'Int'>
  readonly episode: Prisma.FieldRef<"ContinueWatching", 'Int'>
}
    

// Custom InputTypes
/**
 * ContinueWatching findUnique
 */
export type ContinueWatchingFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContinueWatching
   */
  select?: Prisma.ContinueWatchingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContinueWatching
   */
  omit?: Prisma.ContinueWatchingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContinueWatchingInclude<ExtArgs> | null
  /**
   * Filter, which ContinueWatching to fetch.
   */
  where: Prisma.ContinueWatchingWhereUniqueInput
}

/**
 * ContinueWatching findUniqueOrThrow
 */
export type ContinueWatchingFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContinueWatching
   */
  select?: Prisma.ContinueWatchingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContinueWatching
   */
  omit?: Prisma.ContinueWatchingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContinueWatchingInclude<ExtArgs> | null
  /**
   * Filter, which ContinueWatching to fetch.
   */
  where: Prisma.ContinueWatchingWhereUniqueInput
}

/**
 * ContinueWatching findFirst
 */
export type ContinueWatchingFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContinueWatching
   */
  select?: Prisma.ContinueWatchingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContinueWatching
   */
  omit?: Prisma.ContinueWatchingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContinueWatchingInclude<ExtArgs> | null
  /**
   * Filter, which ContinueWatching to fetch.
   */
  where?: Prisma.ContinueWatchingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContinueWatchings to fetch.
   */
  orderBy?: Prisma.ContinueWatchingOrderByWithRelationInput | Prisma.ContinueWatchingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ContinueWatchings.
   */
  cursor?: Prisma.ContinueWatchingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContinueWatchings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContinueWatchings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ContinueWatchings.
   */
  distinct?: Prisma.ContinueWatchingScalarFieldEnum | Prisma.ContinueWatchingScalarFieldEnum[]
}

/**
 * ContinueWatching findFirstOrThrow
 */
export type ContinueWatchingFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContinueWatching
   */
  select?: Prisma.ContinueWatchingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContinueWatching
   */
  omit?: Prisma.ContinueWatchingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContinueWatchingInclude<ExtArgs> | null
  /**
   * Filter, which ContinueWatching to fetch.
   */
  where?: Prisma.ContinueWatchingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContinueWatchings to fetch.
   */
  orderBy?: Prisma.ContinueWatchingOrderByWithRelationInput | Prisma.ContinueWatchingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for ContinueWatchings.
   */
  cursor?: Prisma.ContinueWatchingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContinueWatchings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContinueWatchings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of ContinueWatchings.
   */
  distinct?: Prisma.ContinueWatchingScalarFieldEnum | Prisma.ContinueWatchingScalarFieldEnum[]
}

/**
 * ContinueWatching findMany
 */
export type ContinueWatchingFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContinueWatching
   */
  select?: Prisma.ContinueWatchingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContinueWatching
   */
  omit?: Prisma.ContinueWatchingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContinueWatchingInclude<ExtArgs> | null
  /**
   * Filter, which ContinueWatchings to fetch.
   */
  where?: Prisma.ContinueWatchingWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of ContinueWatchings to fetch.
   */
  orderBy?: Prisma.ContinueWatchingOrderByWithRelationInput | Prisma.ContinueWatchingOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing ContinueWatchings.
   */
  cursor?: Prisma.ContinueWatchingWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` ContinueWatchings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` ContinueWatchings.
   */
  skip?: number
  distinct?: Prisma.ContinueWatchingScalarFieldEnum | Prisma.ContinueWatchingScalarFieldEnum[]
}

/**
 * ContinueWatching create
 */
export type ContinueWatchingCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContinueWatching
   */
  select?: Prisma.ContinueWatchingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContinueWatching
   */
  omit?: Prisma.ContinueWatchingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContinueWatchingInclude<ExtArgs> | null
  /**
   * The data needed to create a ContinueWatching.
   */
  data: Prisma.XOR<Prisma.ContinueWatchingCreateInput, Prisma.ContinueWatchingUncheckedCreateInput>
}

/**
 * ContinueWatching createMany
 */
export type ContinueWatchingCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many ContinueWatchings.
   */
  data: Prisma.ContinueWatchingCreateManyInput | Prisma.ContinueWatchingCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * ContinueWatching createManyAndReturn
 */
export type ContinueWatchingCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContinueWatching
   */
  select?: Prisma.ContinueWatchingSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ContinueWatching
   */
  omit?: Prisma.ContinueWatchingOmit<ExtArgs> | null
  /**
   * The data used to create many ContinueWatchings.
   */
  data: Prisma.ContinueWatchingCreateManyInput | Prisma.ContinueWatchingCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContinueWatchingIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * ContinueWatching update
 */
export type ContinueWatchingUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContinueWatching
   */
  select?: Prisma.ContinueWatchingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContinueWatching
   */
  omit?: Prisma.ContinueWatchingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContinueWatchingInclude<ExtArgs> | null
  /**
   * The data needed to update a ContinueWatching.
   */
  data: Prisma.XOR<Prisma.ContinueWatchingUpdateInput, Prisma.ContinueWatchingUncheckedUpdateInput>
  /**
   * Choose, which ContinueWatching to update.
   */
  where: Prisma.ContinueWatchingWhereUniqueInput
}

/**
 * ContinueWatching updateMany
 */
export type ContinueWatchingUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update ContinueWatchings.
   */
  data: Prisma.XOR<Prisma.ContinueWatchingUpdateManyMutationInput, Prisma.ContinueWatchingUncheckedUpdateManyInput>
  /**
   * Filter which ContinueWatchings to update
   */
  where?: Prisma.ContinueWatchingWhereInput
  /**
   * Limit how many ContinueWatchings to update.
   */
  limit?: number
}

/**
 * ContinueWatching updateManyAndReturn
 */
export type ContinueWatchingUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContinueWatching
   */
  select?: Prisma.ContinueWatchingSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the ContinueWatching
   */
  omit?: Prisma.ContinueWatchingOmit<ExtArgs> | null
  /**
   * The data used to update ContinueWatchings.
   */
  data: Prisma.XOR<Prisma.ContinueWatchingUpdateManyMutationInput, Prisma.ContinueWatchingUncheckedUpdateManyInput>
  /**
   * Filter which ContinueWatchings to update
   */
  where?: Prisma.ContinueWatchingWhereInput
  /**
   * Limit how many ContinueWatchings to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContinueWatchingIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * ContinueWatching upsert
 */
export type ContinueWatchingUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContinueWatching
   */
  select?: Prisma.ContinueWatchingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContinueWatching
   */
  omit?: Prisma.ContinueWatchingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContinueWatchingInclude<ExtArgs> | null
  /**
   * The filter to search for the ContinueWatching to update in case it exists.
   */
  where: Prisma.ContinueWatchingWhereUniqueInput
  /**
   * In case the ContinueWatching found by the `where` argument doesn't exist, create a new ContinueWatching with this data.
   */
  create: Prisma.XOR<Prisma.ContinueWatchingCreateInput, Prisma.ContinueWatchingUncheckedCreateInput>
  /**
   * In case the ContinueWatching was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ContinueWatchingUpdateInput, Prisma.ContinueWatchingUncheckedUpdateInput>
}

/**
 * ContinueWatching delete
 */
export type ContinueWatchingDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContinueWatching
   */
  select?: Prisma.ContinueWatchingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContinueWatching
   */
  omit?: Prisma.ContinueWatchingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContinueWatchingInclude<ExtArgs> | null
  /**
   * Filter which ContinueWatching to delete.
   */
  where: Prisma.ContinueWatchingWhereUniqueInput
}

/**
 * ContinueWatching deleteMany
 */
export type ContinueWatchingDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which ContinueWatchings to delete
   */
  where?: Prisma.ContinueWatchingWhereInput
  /**
   * Limit how many ContinueWatchings to delete.
   */
  limit?: number
}

/**
 * ContinueWatching without action
 */
export type ContinueWatchingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ContinueWatching
   */
  select?: Prisma.ContinueWatchingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ContinueWatching
   */
  omit?: Prisma.ContinueWatchingOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ContinueWatchingInclude<ExtArgs> | null
}
